url: https://kyuhyuk.kr
title: KyuDevelop
author: KyuHyuk Lee
email: lee@kyuhyuk.kr
description: 소프트웨어 개발을 즐기는<br>이규혁의 블로그입니다.
permalink: /article/:categories/:year/:month/:day/:title
show_excerpts: true # set to true to show excerpts on the homepage
google_analytics: UA-61796050-1
github_username: LeeKyuHyuk
generator: KyuHyuk Lee

# Build settings
markdown: kramdown

# Plugins
gems:
  - jekyll-sitemap
