title: KyuDevelop
author: KyuHyuk Lee
email: lee@kyuhyuk.kr
description: > # this means to ignore newlines until "show_exerpts:"
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage
google_analytics: UA-61796050-1

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: KyuHyuk Lee
  tagline: Software Developer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji
